version: "3.3"
services:
  mt5:
    # image: solarkennedy/wine-x11-novnc-docker
    image: gcr.io/ticker-beats/docker-mt5:Dark-Venus-MT5-v1.1
    ports:
      - "8081:8080"
    environment: 
      WINEPREFIX: "/root/prefix64"
      WINEARCH: win64
    volumes:
      - /home/sander/projects/Metatrader5-bin/:/root/metatrader5/
      - /home/sander/projects/mql5:/root/metatrader5/MQL5/
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./common.ini:/root/prefix64/drive_c/myconfiguration.ini
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M